[package]
name = "sand_engine"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndk = "0.6"
ndk-glue = "0.6"
log = "0.4"
